config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
 
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'
  
  get 'products/index'
  
  get 'products/edit'

  get 'products/new'

  get 'products/show'

  get 'orders/index'

  get 'orders/show'

  get 'static_pages/thank_you'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :comments

	validates :name, presence: true

	def highest_rating_comment
	  comments.rating_desc.first
	end
	
	def average_rating
  		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
def index
  if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
  else
    @products = Product.all
  end
end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
  <%= f.label :color %><br>
  <%= f.text_field :color %>
  </div>

  <div class="field">
  <%= f.label :price %><br>
  <%= f.number_field :price, step: 0.01 %>
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>

<!-- <div class="container-fluid" > -->
  <!-- <div class="row"> -->
       <div class="product col-md-3 col-xs-12">
        <% if product.image_url %>
          <%= image_tag(product.image_url, class: "img-responsive") %>
        <% end %>
        <h2><%= product.name %></h2>
        <p><%= product.description %></p>
        <strong><%= product.price %></strong> <br>

          <%= link_to 'Show', product %>
          
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_product_path(product) %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div><!-- /col -->
    <!-- </div> -->
<!-- </div> -->

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% cache(cache_key_for_products) do %>

<!-- <p id="notice"><%= notice %></p> -->

<h1>Products</h1>

  <%= render @products %>

<% end %>
<br>

<div class=" new col-md-12 col-xs-12">
<% if user_signed_in? %>
<%= link_to 'New Product', new_product_path %>
<% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% cache @product do %>

<!-- <p id="notice"><%= notice %></p> -->

<h3>Detailed Productinformation</h3>


<div class="row" data-product-id="<%= @product.id %>">
	<div class="col-lg-12 col-xs-12"><%= image_tag(@product.image_url, width: "350", class: "img-zoom img-responsive", data_zoom_image: @product.image_url) %></div>
	
<div class="col-lg-12 col-xs-12">
	<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
</div>

<div class="col-lg-6 col-xs-12">
	<p>
	  <strong>Name</strong><br>
	  <%= @product.name %>
	</p>

	<p>
	  <strong>Description</strong><br>
	  <%= @product.description %>
	</p>

	<p>
	  <strong>Color</strong><br>
	  <%= @product.color %>
	</p>

	<p>
	  <strong>Price</strong>
	  <%= number_to_currency(@product.price) %>
	</p>

	<p>
		<strong>Average Rating</strong>
		<div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> 
	</p>

	<p>
		<strong>Highest Comment</strong><br>
		<%= @product.highest_rating_comment.try(:body) %>
	</p>

	<%= form_tag "/payments/create" do %>
		<%= hidden_field_tag(:product_id, @product.id) %>
		<%= render partial: "shared/stripe_checkout_button" %>
	<% end %><br><br>


	<%= link_to 'Edit', edit_product_path(@product) %>|
	<%= link_to 'Back', products_path %>
<% end %>
</div>

<!-- _new_comment.html.erb -->
<div class="col-lg-6 col-xs-12">
	<% if signed_in? %>
<p>Last Comments</p>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments", :required => true %><br>
      <%= f.text_area :body, :required => true %>
    </p>

    <p>
    	<div class="rating"></div>
	</p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>


	<!--  _comments.html.erb -->
	<div class="dropdown">
	  <button class="dropbtn">Dropdown</button>
	  <div class="dropdown-content">
	  	<a>
		<div class="product-reviews">
			<p><strong>Latest Commets</strong></p>
		    <% @comments.each do |comment| %>
		        <div class="row">
		            <hr><div class="rated" data-score="<%= comment.rating %>"></div>
		            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
	    			<% if signed_in? && current_user.admin? %>
	       			<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
	    			<% end %></p>
		            <p><%= "Rating: #{comment.rating}/5" %></p>
		            <p><%= comment.body %></p>
		        </div>
		    <% end %>
			<%= will_paginate @comments %>
		</div>
		</a>

	  </div>
	</div>
</div>